services:

  web:
    build: .
    container_name: computer-inventory-web
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: computer-inventory-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: computer_inventory
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
